"""
Task type constants.
"""

REGRESSION = "regression"
BINARY_CLASSIFICATION = "binary_classification"
MULTICLASS_CLASSIFICATION = "multiclass_classification"

TABULAR = "tabular"
FEATURE_SEQUENCE = "feature_sequence"

CLASSIFICATION_TYPES = {BINARY_CLASSIFICATION, MULTICLASS_CLASSIFICATION}
INPUT_MODES = {TABULAR, FEATURE_SEQUENCE}
TASK_TYPES = {REGRESSION, BINARY_CLASSIFICATION, MULTICLASS_CLASSIFICATION}
